### ISSUE TITLE
Error in IpToCountryRepository.php : on too many /../../../../../var/magefan/geoip/GeoLite2-Country.mmdb

### ISSUE THREAD

**Issue by ZaneCEO** [magefan/module-geoip#11]
There is an error here: https://github.com/magefan/module-geoip/blob/master/Model/IpToCountryRepository.php#L128

Since CWD is `<magento>/vendor/magefan/module-geoip/Model`, if you go up `'/../../../../../` you end up in the directory ABOVE Magento, thus `var/magefan/geoip/GeoLite2-Country.mmdb` is ALWAYS non-existant.

Also, please use the recommended function to get the `var` directory. 

Also, please assign the path to a variable, so you don't have to write the same code twice.

This is my quick and dirty patch:

````php

....
                    $geoDbFile =
                        \Magento\Framework\App\ObjectManager::getInstance()
                            ->get('\Magento\Framework\Filesystem\DirectoryList')
                            ->getPath('var') . DIRECTORY_SEPARATOR . 'magefan/geoip/GeoLite2-Country.mmdb';

                    if ( file_exists($geoDbFile) ) {
                        $datFile = $geoDbFile;

...

                    } else {
....
````

Even better: use DI instead of `ObjectManager::getInstance`.

Also: that function is too long. Please put a guard clause at the beginning and split the code in multiple function: were to split is obvious just looking at the code layout.

Thanks.

**Comment by magefan** [comment]
@ZaneCEO , thank you for your report. Please use this fix https://github.com/magefan/module-geoip/commit/6c723241ed64e9141dd115139a7f6aa4be8bc171 . 

Let us know if it works well for you.

**Comment by ZaneCEO** [comment]
Confirmed, thanks!
