### ISSUE TITLE
The IP database https://magefan.com/media/geoip/GeoLite2-Country.mmdb is outdated

### ISSUE THREAD

**Issue by ZaneCEO** [magefan/module-geoip#12]
The module downloads it's IP database here https://github.com/magefan/module-geoip/blob/master/Model/GeoIpDatabase/MaxMind.php#L18

As you can see with `curl -sSL -D - https://magefan.com/media/geoip/GeoLite2-Country.mmdb -o /dev/null`, that file was `last-modified: Fri, 29 Oct 2021 10:27:55 GMT`

![image](https://user-images.githubusercontent.com/5873880/186158475-909dc4b1-2e44-4d4c-aad8-12479acffa9d.png)

It's about one year old, and you can tell: an IP such as `85.204.70.110` is from France, and https://www.maxmind.com/en/geoip2-precision-demo?ip_address=85.204.70.110 reports this correctly. But the module database is outdated, and so the module reports it as "Great Britain".

This is a by-the-book example of why is a terrible practice to copy and host live data. You should at very least update the database once per month or, even better, allow the user to insert an apikey and get it from maxmind.com directly.

Thanks

**Comment by magefan** [comment]
@ZaneCEO , GeoLite2-Country.mmdb has been updated. Please press "Update MaxMind GeoIP Database Now" in the Stores > Configuration > Magefan Extensions > GeoIP Database

**Comment by ZaneCEO** [comment]
@magefan Yes, your mirrored copy has been updated. Still:

> This is a by-the-book example of why is a terrible practice to copy and host live data. You should at very least update the database once per month or, even better, allow the user to insert an apikey and get it from maxmind.com directly.

**Comment by magefan** [comment]
@ZaneCEO ,

The new feature has been added. https://github.com/magefan/module-geoip/commit/d5f7f37c3f0e5f2a15acfa51132e970fd47ae484

It allows you to use MaxMind License Key and Api to update the database.
