### ISSUE TITLE
Extension crashes Magento admin when Magento_AdminNotification is disabled

### ISSUE THREAD

**Issue by slavko98** [magefan/module-geoip#15]
Hello magefan team!

Today I stumbled upon this strange error, when entering the admin: `SQLSTATE[42S02]: Base table or view not found: 1146 Table 'magento.adminnotification_inbox' doesn't exist, query was: SELECT adminnotification_inbox.* FROM adminnotification_inbox WHERE (title = 'NEW Magento 2 Product Tabs Extension!') AND (url = 'https://magefan.com/magento-2/extensions/product-tabs?utm_source=website&amp;utm_medium=admin-ntf&amp;utm_campaign=product-tabs ')`

Our project has the `Magento_AdminNotification` module disabled, so the `adminnotification_inbox` was never created in the database. Is it possible that you depend on this table existing in the system without checking? This is quite bad, because is completely disables the admin area by throwing these ugly exceptions:

![magefans requires magento adminnotifications](https://user-images.githubusercontent.com/10711002/192757066-55fdac43-9bf0-4167-a544-ac09930d817e.png)

Would be cool if you fixed this :-) Perhaps checking for the existance of the `adminnotification_inbox` would be enough.

**Comment by magefan** [comment]
@slavko98 , thank you for your report. We're working on this issue.

**Comment by magefan** [comment]
This issue is related to https://github.com/magefan/module-community package and has been fixed in magefan/module-community v2.1.12
