### ISSUE TITLE
Fatal error addFielToFilter()

### ISSUE THREAD

**Issue by Axel29** [magefan/module-geoip#2]
Hi,

If php-geoip is not installed, there's a fallback to the database tables but the code breaks in this case.

Here's the error:

> Fatal error: Uncaught Error: Call to undefined method Magefan\GeoIp\Model\ResourceModel\IpToCountry\Collection::addFielToFilter() in /var/www/vendor/magefan/module-geoip/Model/IpToCountryRepository.php:56 Stack trace: #0 /var/www/vendor/magefan/module-geoip/Model/IpToCountryRepository.php(74): Magefan\GeoIp\Model\IpToCountryRepository->getCountryCode('127.0.0.1') #1 /var/www/app/code/Clrz/GeoIp/Helper/Popin.php(193): Magefan\GeoIp\Model\IpToCountryRepository->getVisitorCountryCode() #2 /var/www/app/code/Clrz/GeoIp/view/frontend/templates/switch/languages.phtml(35): Clrz\GeoIp\Helper\Popin->getUserCountry() #3 /var/www/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/var/www/projec...') #4 /var/www/vendor/magento/framework/View/Element/Template.php(270): Magento\Framework\View\TemplateEngine\Php->render(Object(Clrz\GeoIP\Block\Store\Switcher\Interceptor), '/var/www/projec...', Array) #5 /var/www/generated/code/Clrz/GeoIP/Block/Store/Switcher/Interce in /var/www/vendor/magefan/module-geoip/Model/IpToCountryRepository.php on line 56

**Comment by Axel29** [comment]
EDIT : Found the issue (took me some time to really READ the error ^^")

You used "addFielToFilter", there's a "d" missing for "addFiel**d**ToFilter" for both lines 56 and 57.

**Comment by magefan** [comment]
Thank you. Making correction.

**Comment by magefan** [comment]
The fix was made. Please try to update the extension to the version 2.0.1

**Comment by Axel29** [comment]
That was fast :) Thanks, it works perfectly even without php-geoip now!
