### ISSUE TITLE
Magento 2.2.2 - Maxmind GeoIP WebService

### ISSUE THREAD

**Issue by Vikram0811** [magefan/module-geoip#3]
Hi,

Can this module used for Maxmind GeoIP2 WebService?

https://dev.maxmind.com/geoip/geoip2/web-services/

Thanks

**Comment by magefan** [comment]
Hello @Vikram0811 , it should already use maxmind, as our magento geoip extension has in requirements this package https://packagist.org/packages/geoip2/geoip2
and geoip2/geoip2 use
maxmind-db/reader: ~1.0
maxmind/web-service-common: ~0.5
