### ISSUE TITLE
getting memory error: Fatal error: Allowed memory size of 1073741824 bytes exhausted 

### ISSUE THREAD

**Issue by kul3101** [magefan/module-geoip#4]
After installing module by composer or zip archive when run command setup:di:compile getting error for Allowed memory size.

Here is attached screenshot.

![geoip_error](https://user-images.githubusercontent.com/23148892/45807320-de1def00-bce0-11e8-8476-d22ce10dc82d.png)

**Comment by magefan** [comment]
Hello @kul3101 , it's a common magneto 2 issue. Please check this article to learn how you can fix it https://magefan.com/blog/bin-magento2-fatal-error-allowed-memory-size/
