### ISSUE TITLE
Varnish support

### ISSUE THREAD

**Issue by Tjitse-E** [magefan/module-geoip#6]
Does this module work with Varnish caching enabled?

**Comment by magefan** [comment]
@Tjitse-E , thank you for your question. This module is not a self-sufficient module, it is pease of code that works with different GeoIp databases and provides the functionality to define visitor country based on the IP (GeoLocation). If you want to get an answer I this module works with Varnish, the answer depends on how you will use it.

We use magefan/module-geoip in these our modules
1. [Magento 2 Auto Currency Switcher Extension](https://magefan.com/magento-2-currency-switcher-auto-currency-by-country)
2. [Magento 2 Auto Language Switcher Extension](https://magefan.com/magento-2-auto-language-switcher)

both of these auto-switcher extensions compatible (work) with varnish.

Let us know if you have any other questions.

**Comment by Tjitse-E** [comment]
Hi @magefan.

We've created a [auto country select](https://github.com/Vendic/magento2-geoip-country-preselect) module on top of Magefan GeoIP.  I'll test in the coming weeks if it will work with Varnish.

Thanks for the module so far!

**Comment by magefan** [comment]
@Tjitse-E , We have checked the code of your module (vendic/magento2-geoip-country-preselect), and it will have an issue with Magento Page Cache and will not work properly with varnish. We recommend to use [Magento 2 Auto Currency Switcher](https://magefan.com/magento-2-currency-switcher-auto-currency-by-country) by [Magefan](https://magefan.com). It already does what you trying to achieve, and works perfectly with Magento build in Page Cache and Varnish, it will allow you to save time and money.
